name: Create PR in a remote ArthurBandaryk/PR-bot repo

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  Try-Update-Eventuals:
    runs-on: ubuntu-latest
    steps:
      - name: Install buildifier for .bzl files
        run: brew install buildifier
        shell: bash

      - uses: actions/checkout@v3
        with:
          submodules: "recursive"  

      - name: Grab current commit and shallow_since
        id: current_info
        run: |
          echo ::set-output name=current_commit::$(git log -n 1 --pretty=format:"%H")
          echo ::set-output name=current_shallow_since::$(git log -n 1 --date=raw --pretty=format:"%cd")   

      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.main_lib_pr_bot_secret }}
          repository: ArthurBandaryk/PR-bot

      - name: Update WORKSPACE.bazel
        run: |
          current_commit="${{ steps.current_info.outputs.current_commit }}"
          current_shallow_since="${{ steps.current_info.outputs.current_shallow_since }}"
          chmod +x dev-tools/.github/workflows/scripts/update-eventuals-git-repository.sh
          ./dev-tools/.github/workflows/scripts/update-eventuals-git-repository.sh WORKSPACE.bazel $current_commit "$current_shallow_since"
        shell: bash  

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update eventuals in git_repository bazel rule
          title: Update eventuals
          body: Update eventuals commit and shallow_since in 'git_repository' bazel rule
          branch: update-eventuals
          base: main
          add-paths: WORKSPACE.bazel
          token: ${{ secrets.main_lib_pr_bot_secret }}
